### ISSUE TITLE
code does not work with python-3.x

### ISSUE THREAD

**Issue by vapier** [GoogleCloudPlatform/gcs-oauth2-boto-plugin#10]
oauth2_client.py does:

<pre>      fd = os.open(cache_file, flags, 0600)</pre>

python-3.x requires that to be 0o0600.  same bug can be seen in test_oauth2_client.py.

**Comment by bobobo1618** [comment]
Even after this is fixed there are a ton more issues. I ran `2to3` and it fixed a bunch but there are still some issues, particularly with Unicode.

**Comment by vapier** [comment]
probably true, but i don't think we need to fix everything in one go.  there's no reason independent things can't be fixed.

**Comment by bivald** [comment]
Any news on Python-3x compability for gcs-oauth2-boto-plugin?

**Comment by bivald** [comment]
I've forked a python-3x compatible branch on https://github.com/enplore/gcs-oauth2-boto-plugin
I'm using it for python 2.7 and python 3.4 and as far as I can test, it works (all test passes as well)

**Comment by houglum** [comment]
Major version 2 introduced Py3 compatibility; closing this.

**Comment by vapier** [comment]
commit 9425f1dd80716888ae2a95b4d572de068f2f9c14 fixed things
