### ISSUE TITLE
Import fails since oauth2client update.

### ISSUE THREAD

**Issue by RobertAtomic** [GoogleCloudPlatform/gcs-oauth2-boto-plugin#21]
It seems that there has been a breaking change to oauth2client ([#401](https://github.com/google/oauth2client/issues/401)) that is affecting gcs-oauth2-boto-plugin.  Pinning oauth2client to 1.5.2 seems to fix it, but presumably gcs-oauth2-boto-plugin should be updated to use the new hotness.

**Comment by doczoidberg** [comment]
did you found a solution other than downgrading?

**Comment by RobertAtomic** [comment]
No, I pinned by requirements file to 1.5.2 and left it at that.

**Comment by mikesjqubit** [comment]
Are there any plans to fix this?  Currently this seems to have made boto and bigquery incompatible.

**Comment by romange** [comment]
Guys this patch https://github.com/GoogleCloudPlatform/gcs-oauth2-boto-plugin/pull/23
fixed the problem for us.

**Comment by bivald** [comment]
Path #23 worked for me

**Comment by houglum** [comment]
Closing as obsolete.
