### ISSUE TITLE
Failing to install gsutil and latest gcs-oauth2-boto-plugin

### ISSUE THREAD

**Issue by mhagen-vmware** [GoogleCloudPlatform/gcs-oauth2-boto-plugin#24]
Downloading gcs-oauth2-boto-plugin-1.13.tar.gz
  Running setup.py (path:/tmp/pip-build-vqbH5h/gcs-oauth2-boto-plugin/setup.py) egg_info for package gcs-oauth2-boto-plugin
    error in gcs-oauth2-boto-plugin setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in gcs-oauth2-boto-plugin setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

But if I do pip install gcs-oauth2-boto-plugin==1.12 it succeeds.

**Comment by mhagen-vmware** [comment]
@thobrla  Any chance we can get this fixed quick?  It is really blocking a project I am working on...

**Comment by thobrla** [comment]
Yes, fixing this is a high priority.  I suspect it has to do with the multi-version string (>=1.5.2, !=2.0.*), though this should be legal according to https://www.python.org/dev/peps/pep-0440/#id51

**Comment by thobrla** [comment]
1.14 has been pushed to PyPi and 1.13 removed - please let me know if this doesn't fix the issue for you.

**Comment by mhagen-vmware** [comment]
Fix is confirmed, thanks for the quick turn around!
