### ISSUE TITLE
Consider tagging releases on github

### ISSUE THREAD

**Issue by bsiegert** [GoogleCloudPlatform/gcs-oauth2-boto-plugin#38]
Hi, packager of http://pkgsrc.se/net/py-gcs-oauth2-boto-plugin here.

It would be easier to follow new releases if they were tagged, with release notes, in Github. Or is there a different recommended way to keep up with upstream releases?

**Comment by houglum** [comment]
Retroactively added commit tags when I pushed out v2.2.  Marking as closed.
